
//order
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ORDER_PRODUCT = 'ORDER_PRODUCT';
export const ADD_PRODUCT= 'ADD_PRODUCT';
export const REMOVE_PRODUCT= 'REMOVE_PRODUCT';
export const ELIMINATE_PRODUCT= 'ELIMINATE_PRODUCT';
export const SEND_ORDER= 'SEND_ORDER';
export const PURCHASE_ORDER_SUCCESS= 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAIL= 'PURCHASE_ORDER_FAIL';
export const PURCHASE_ORDER_START= 'PURCHASE_ORDER_START';
export const INITIAL_STATE= 'INITIAL_STATE';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';
export const MENU_SELECTED = 'MENU_SELECTED';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const ORDER_SUCCESS_TOGGLE = 'ORDER_SUCCESS_TOGGLE';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'

//auth
export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_ERROR= 'AUTH_ERROR';
export const AUTH_LOGOUT= 'AUTH_LOGOUT';

//shop
export const ORDER_SUMARY_RESET= 'ORDER_SUMARY_RESET';
export const ORDER_SUMMARY_ADD= 'ORDER_SUMMARY_ADD';
