export const TOGGLE_MENU = 'TOGGLE_MENU';

export const LOADING_ERROR = 'LOADING_ERROR';
export const LOADING_IN_PROGRESS = 'LOADING_IN_PROGRESS';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ELIMINATE_PRODUCT = 'ELIMINATE_PRODUCT';

export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';

export const CONFIRM_ORDER_PRODUCTS = 'CONFIRM_ORDER_PRODUCTS';
export const CONFIRM_SHIPPING_DATA = 'CONFIRM_SHIPPING_DATA';
export const CONFIRM_PAYMENT_DATA = 'CONFIRM_PAYMENT_DATA';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
